name: workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo hello vinod
              run: echo "Hello vinod"
            - name: multiline cmd
              run: |
                   node -v
                   npm -v
